<?php

/**
 * @file
 * Databasics module.
 */

/**
 * Implements hook_node_view().
 */
function databasics_node_view($node, $view_mode = 'full') {
  if ($view_mode == 'full') {
    if (empty($_SESSION['node_views'][$node->nid])) {
      $_SESSION['node_views'][$node->nid] = array('view_count' => 0);
    }
    $_SESSION['node_views'][$node->nid]['view_count']++;

    // Set up an array of placeholders to pass to t().
    $t_args = array(
      '%num' => $record->view_count,
    );

    $node->content['node_views'] = array(
      '#markup' => t('You have viewed this page %num times.', $t_args),
      '#weight' => 10,
    );
  }
}
